### ISSUE TITLE
utm_content parameter is not stripped in the pages report

### ISSUE THREAD

**Issue by MichalTomczak** [PiwikPRO/plugin-AdvancedCampaignReporting#19]
While tracking campaign using utm_content parameter with Advanced Campaign Reporting active, the utm parameter is displayed as a different page entrance, without the plugin this does not happen. Please see the screenshot
![screenshot 2015-03-18 12 50 36](https://cloud.githubusercontent.com/assets/8134608/6708100/9afaf468-cd6d-11e4-9dff-28ebf45d267c.png)

**Comment by mattab** [comment]
Hi @MichalTomczak thanks for the report.

It looks like some of the default URL parameters to exclude are not actually excluded correctly. We will fix it in soon!

**Comment by peterbo** [comment]
This was already fixed here: https://github.com/piwik/piwik/pull/7146

**Comment by mattab** [comment]
@peterbo good point - thanks for reminding me. I forgot to release anew plugin version after your fix!

@MichalTomczak we released a new version of the plugin - can you try again if it works now? version 1.0.7

**Comment by RMastop** [comment]
Hi @mattab,
Is there a typo in version number? After the update it still shows me there is an update to version 1.0.6.
![image](https://cloud.githubusercontent.com/assets/7987117/6929283/e2e37cfa-d7f9-11e4-819f-539c54bf7c48.png)

**Comment by mattab** [comment]
Hi @RMastop - oh that's strange. Do you still get this 1.0.6->1.0.6 now? 

if you click on "Check for updates" does it work better?

**Comment by RMastop** [comment]
Hi @mattab,
Working fine after update to 1.0.8
Tested log-analytics and utm_content is removed correctly from those imports.

**Comment by mattab** [comment]
Thanks for confirmation @RMastop

**Comment by MichalTomczak** [comment]
the fix for removing utm_content from URL is not working correctly.
I still see them in page URL report.
When I look at the following report:
https://statistiek.rijksoverheid.nl/index.php?module=CoreHome&action=index&idSite=4&period=day&date=2015-04-20#/module=Actions&action=menuGetPageUrls&idSite=4&period=day&date=2015-04-20
and search for "?utm_", I get a list of URLs containing the data.
Looking at the plugin version, I see version 1.0.8, this is the version that should fix the issue.
Could you look into this?

**Comment by mattab** [comment]
Hi @MichalTomczak 
it only works for data going forward after 1.0.8 was installed. The previous data will still show the utm_content parameters. It seems to work for me here.

**Comment by RMastop** [comment]
Could it be that a minimum version of Piwik is needed for this? In my case I'm running v2.9.1, the utm_content parameter is still visible on data tracked after the plugin was updated.

**Comment by mattab** [comment]
@RMastop Correct you will need 2.11.0 or newer to have this feature working as a new Event was added in https://github.com/piwik/piwik/pull/7146

**Comment by mattab** [comment]
I'm closing as it should work. if it does not work with 2.11.1 or newer, please re-open and I'll investigate
